/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Scheduler;

import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static org.apache.derby.impl.sql.compile.SQLParserConstants.SQL;
import static org.eclipse.persistence.jpa.jpql.parser.Expression.SQL;
import static org.eclipse.persistence.logging.SessionLog.SQL;

/**
 *
 * @author Tolu
 */
public class Welcome1 extends javax.swing.JFrame {

    private Customer customer= new Customer(); 
    private Day date= new Day();
    private Flight flight= new Flight(); 
    
    public Welcome1() {
        initComponents();
        CustomerNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomer().toArray()));
        BookingDateCombo.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        BookingFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
        CustomerStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomer().toArray()));
        CancelCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomer().toArray()));
        CancDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        AddCustomerText = new javax.swing.JTextField();
        AddCustomerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        AddDaySpinner = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        AddDayButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        NumSeatsSpinner = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        AddFlightButton = new javax.swing.JButton();
        FlightNameText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BookingFlightCombo = new javax.swing.JComboBox<>();
        BookingDateCombo = new javax.swing.JComboBox<>();
        CustomerNameCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddBookingButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BookStatus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        StatusFlightCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StatusDateCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ShowWaitlistButton = new javax.swing.JButton();
        ShowStatusButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        BookingWaitlistTable = new javax.swing.JTable();
        CustomerStatusButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        CustomerStatusCombo = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        DropFlightCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        DropFlightTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CancelCustomerCombo = new javax.swing.JComboBox<>();
        CancCustButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        CancDateCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        CancelBookingTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        AddCustomerButton.setText("Add");
        AddCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Customer Name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AddCustomerButton)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(AddCustomerText, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCustomerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(80, 80, 80)
                .addComponent(AddCustomerButton)
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Add Customer", jPanel1);

        AddDaySpinner.setModel(new javax.swing.SpinnerDateModel());

        jLabel11.setText("Date:");

        AddDayButton.setText("Add");
        AddDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(AddDayButton)
                        .addGap(78, 78, 78))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(AddDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(AddDayButton)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Day", jPanel5);

        jLabel9.setText("Flight Name: ");

        jLabel10.setText("Number of Seats:");

        AddFlightButton.setText("Add");
        AddFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FlightNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(371, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddFlightButton)
                .addGap(94, 94, 94))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(FlightNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(NumSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(AddFlightButton)
                .addGap(72, 72, 72))
        );

        jTabbedPane1.addTab("Add Flight", jPanel4);

        BookingFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BookingDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CustomerNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Flight:");

        jLabel3.setText("Date:");

        AddBookingButton.setText("Confirm");
        AddBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookingButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Customer Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookingDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BookingFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(BookStatus))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(AddBookingButton)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(BookingFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BookStatus)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(57, 57, 57)
                .addComponent(AddBookingButton)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking", jPanel2);

        StatusFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Date:");

        StatusDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Flight: ");

        ShowWaitlistButton.setText("WaitList");
        ShowWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowWaitlistButtonActionPerformed(evt);
            }
        });

        ShowStatusButton.setText("Booked LIst");
        ShowStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowStatusButtonActionPerformed(evt);
            }
        });

        BookingWaitlistTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(BookingWaitlistTable);

        CustomerStatusButton.setText("Customer Status");
        CustomerStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerStatusButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Customer:");

        CustomerStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(StatusFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(CustomerStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(StatusDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(ShowStatusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShowWaitlistButton)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerStatusButton)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(CustomerStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StatusDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowStatusButton)
                    .addComponent(ShowWaitlistButton)
                    .addComponent(CustomerStatusButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        jTabbedPane1.addTab("Status", jPanel3);

        jLabel15.setText("Flight Name:");

        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Drop Flight");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DropFlightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropFlightTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel15)
                .addGap(37, 37, 37)
                .addComponent(DropFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(DropFlightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(141, 141, 141))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DropFlightCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(DropFlightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drop Flight", jPanel7);

        jLabel13.setText("Customer Name:");

        CancelCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CancCustButton.setText("Cancel Customer");
        CancCustButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancCustButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Flight Date:");

        CancDateCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CancelBookingTextArea.setColumns(20);
        CancelBookingTextArea.setRows(5);
        jScrollPane1.setViewportView(CancelBookingTextArea);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancCustButton)
                .addGap(87, 87, 87))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(CancelCustomerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CancDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(CancCustButton)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancel Customer", jPanel6);

        jLabel8.setText("FLIGHT SCHEDULER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowStatusButtonActionPerformed
        Date parsed = Date.valueOf(StatusDateCombo.getSelectedItem().toString());
        BookingWaitlistTable.setModel(Booking.settingJTable(parsed, StatusFlightCombo.getSelectedItem().toString()));
    }//GEN-LAST:event_ShowStatusButtonActionPerformed

    private void ShowWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowWaitlistButtonActionPerformed

        Date parsed = Date.valueOf(StatusDateCombo.getSelectedItem().toString());
        BookingWaitlistTable.setModel(Waitlist.settingJTable(parsed));
    }//GEN-LAST:event_ShowWaitlistButtonActionPerformed

    private void AddBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookingButtonActionPerformed
        String flightType = (String) BookingFlightCombo.getSelectedItem();
        String customerName =  (String) CustomerNameCombo.getSelectedItem();
        Date flightDate=null;
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date date = sdf1.parse((String) BookingDateCombo.getSelectedItem());
            flightDate = new java.sql.Date(date.getTime());
        } catch (ParseException ex) {
            Logger.getLogger(Welcome1.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
        int total_seats = Flight.getSeats(flightType);
        int booked_seats = Booking.getBookCount(flightType, flightDate);
        
        java.sql.Timestamp customerPosition = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        System.out.println(total_seats);
        System.out.println(booked_seats);
        if (total_seats > booked_seats)
        {
            Booking.addBooking(customerName, flightDate, flightType);
            BookStatus.setText("Customer was booked.");
            
        }
        else
        {
            Waitlist.addWaitlist(customerName, flightDate, flightType, customerPosition);
            BookStatus.setText("Customer was waitlisted");       
        }
    }//GEN-LAST:event_AddBookingButtonActionPerformed

    private void AddCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerButtonActionPerformed
        int result = customer.addCustomer(AddCustomerText.getText());
        
        if(result == 1)
            JOptionPane.showMessageDialog(this, "Person added!","Person added", JOptionPane.PLAIN_MESSAGE);
        else
             JOptionPane.showMessageDialog(this, "Person not Added!","Error", JOptionPane.PLAIN_MESSAGE); 
        
        CustomerNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomer().toArray()));
        CustomerStatusCombo.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomer().toArray()));
        CancelCustomerCombo.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomer().toArray()));
        
    }//GEN-LAST:event_AddCustomerButtonActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        CustomerNameCombo.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomer().toArray()));
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void AddFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightButtonActionPerformed
  int result = Flight.addFlight(FlightNameText.getText(),(int) NumSeatsSpinner.getValue());
        
        if(result == 1)
            JOptionPane.showMessageDialog(this, "Flight added!","Person added", JOptionPane.PLAIN_MESSAGE);
        else
             JOptionPane.showMessageDialog(this, "Flight not Added!","Error", JOptionPane.PLAIN_MESSAGE); 
        
        BookingFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));

        
    }//GEN-LAST:event_AddFlightButtonActionPerformed

    private void AddDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDayButtonActionPerformed

        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd"); 
        String spinnerValue = formater.format(AddDaySpinner.getValue()); 
        Date date = Date.valueOf(spinnerValue);
        int result = Day.addDate(date);
        
        if(result == 1)
            JOptionPane.showMessageDialog(this, "Date added!","Person added", JOptionPane.PLAIN_MESSAGE);
        else
             JOptionPane.showMessageDialog(this, "Date not Added!","Error", JOptionPane.PLAIN_MESSAGE);
        
        StatusDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
        CancDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
        BookingDateCombo.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
        
    }//GEN-LAST:event_AddDayButtonActionPerformed

    private void CancCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancCustButtonActionPerformed
        
        String cancel_Customer = CancelCustomerCombo.getItemAt (CancelCustomerCombo.getSelectedIndex());
        //String cancel_Date = CancDateCombo.getItemAt (CancDateCombo.getSelectedIndex());
        Date cancel_Date = Date.valueOf(CancDateCombo.getSelectedItem().toString());
        int number = 0;
        String status = "";
        String currentFlight;
        currentFlight = Booking.getBookingByCustDate(cancel_Customer, cancel_Date);
        if (currentFlight != null)
        {
            System.out.println("Customer was found in bookings, removing now");
            System.out.println("Current flight is " + currentFlight);
            Booking.cancelBooking(cancel_Customer, cancel_Date);
            status += "Customer " + cancel_Customer + " Cancelled.";
            
            String book_customer = Waitlist.waitlistByFlightDate(currentFlight, cancel_Date);
            if (book_customer != null)
            {
                java.sql.Timestamp newTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
                Booking.bookByFlightDate(cancel_Date,currentFlight, book_customer, newTimestamp);
                status +=  book_customer + " was added";
                Waitlist.cancelWaitlist(book_customer, cancel_Date);
            }
            
            
            CancelBookingTextArea.setText(status);
            
        }
        else
        {
            System.out.println("Customer was not found in bookings, Checking Waitlist");
            number = Waitlist.cancelWaitlist(cancel_Customer, cancel_Date);
            
            if (number == 0)
            {
                CancelBookingTextArea.setText("Selected customer is not booked/waitlisted for this date");
            }
            else
            {
                CancelBookingTextArea.setText("Selected customer removed from waitlist for this date");
            }
        }
    }//GEN-LAST:event_CancCustButtonActionPerformed

    private void CustomerStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerStatusButtonActionPerformed
        
        try {
            BookingWaitlistTable.setModel (Customer.settingJTable((String) CustomerStatusCombo.getSelectedItem()));
        } catch (SQLException ex) {
            Logger.getLogger(Welcome1.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_CustomerStatusButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String drop_flight = DropFlightCombo.getItemAt (DropFlightCombo.getSelectedIndex());;
        Flight.RemoveFlight(drop_flight);
        if (drop_flight != null)
        {
            DropFlightTextField.setText("Flight has been dropped");
        }
        Flight.RemoveBookingsOfDeletedFlight(drop_flight);
        Flight.RemoveWaitListOfDeletedFlight(drop_flight);
        Flight.getNamesOfPassangersBooked(drop_flight);
        Flight.getDatesOfPassangersBooked(drop_flight);
        Flight.getNamesOfPassangersWaitListed(drop_flight);
        
        //int result = Flight.deleteFlight( (String) DropFlightCombo.getSelectedItem());
        
        //if(result == 1)
        //    JOptionPane.showMessageDialog(this, "Flight deleted!","Flight dropped", JOptionPane.PLAIN_MESSAGE);
        //else
        //     JOptionPane.showMessageDialog(this, "Flight not deleted!","Error", JOptionPane.PLAIN_MESSAGE); 
        
        BookingFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        DropFlightCombo.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DropFlightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropFlightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropFlightTextFieldActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookingButton;
    private javax.swing.JButton AddCustomerButton;
    private javax.swing.JTextField AddCustomerText;
    private javax.swing.JButton AddDayButton;
    private javax.swing.JSpinner AddDaySpinner;
    private javax.swing.JButton AddFlightButton;
    private javax.swing.JLabel BookStatus;
    private javax.swing.JComboBox<String> BookingDateCombo;
    private javax.swing.JComboBox<String> BookingFlightCombo;
    private javax.swing.JTable BookingWaitlistTable;
    private javax.swing.JButton CancCustButton;
    private javax.swing.JComboBox<String> CancDateCombo;
    private javax.swing.JTextArea CancelBookingTextArea;
    private javax.swing.JComboBox<String> CancelCustomerCombo;
    private javax.swing.JComboBox<String> CustomerNameCombo;
    private javax.swing.JButton CustomerStatusButton;
    private javax.swing.JComboBox<String> CustomerStatusCombo;
    private javax.swing.JComboBox<String> DropFlightCombo;
    private javax.swing.JTextField DropFlightTextField;
    private javax.swing.JTextField FlightNameText;
    private javax.swing.JSpinner NumSeatsSpinner;
    private javax.swing.JButton ShowStatusButton;
    private javax.swing.JButton ShowWaitlistButton;
    private javax.swing.JComboBox<String> StatusDateCombo;
    private javax.swing.JComboBox<String> StatusFlightCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
